<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class Kd03UpdateRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'no_cust' => 'nullable',
            'kd06_id' => 'nullable',
            'kd04_id' => 'nullable',
            'kd05_id' => 'nullable',
            'kd11_id' => 'nullable',
            'kd14_id' => 'nullable',
            'additional_id' => 'nullable',
            'class' => 'nullable',
            'title' => 'nullable',
            'kd6no_cust' => 'nullable',
            // 'kode_cust' => 'nullable',
            'kode_county' => 'nullable',
            'kota' => 'nullable',
            'email' => 'nullable',
            'telp' => 'nullable',
            'npwp' => 'nullable',
            'short_name' => 'nullable',
            'nama1' => 'nullable',
            'nama2' => 'nullable',
            'street' => 'nullable',
            'negara' => 'nullable',
            'addit' => 'nullable',
            'postal_code' => 'nullable',
            'po_box' => 'nullable',
            'kd6tax' => 'nullable',
            'mobile' => 'nullable',
            'home' => 'nullable',
            'fax' => 'nullable',
            'status' => 'nullable',
            'tanggal' => 'date|nullable',

            // 'created_by' => 'nullable',
            // 'submitted_by' => 'nullable',
            // 'status_form' => 'nullable',
            // 'aprv1_by' => 'nullable',
            // 'aprv2_by' => 'nullable',
            // 'inputted_by' => 'nullable',
            // 'finished_by' => 'nullable',
            // 'rejectted_by' => 'nullable',
            // 'reject_reason' => 'nullable',


            // kd04
            'credit_limit' => 'nullable',
            'payterm' => 'nullable',
            'alasan_perubahan' => 'nullable',
            'history_pembayaran' => 'nullable',
            'kd4no_cust' => 'nullable',
            'no_debitor' => 'nullable',
            'no_creditor' => 'nullable',
            'no_group_cust' => 'nullable',
            'credit_cust' => 'nullable',
            'credit_from' => 'nullable',
            'credit_to' => 'nullable',
            'credit_line_check' => 'nullable',
            'block_delivery' => 'nullable',
            'block' => 'nullable',
            'block_reason' => 'nullable',

            // kd05
            'no_cust1' => 'nullable',
            'no_cust2' => 'nullable',
            'no_cust3' => 'nullable',
            'addresscode1' => 'nullable',
            'addresscode2' => 'nullable',
            'addresscode3' => 'nullable',
            'address_code1' => 'nullable',
            'title1' => 'nullable',
            'negara1' => 'nullable',
            'kode_county1' => 'nullable',
            'kota1' => 'nullable',
            'email1' => 'nullable',
            'telp1' => 'nullable',
            'npwp1' => 'nullable',
            'short_name1' => 'nullable',
            'nama11' => 'nullable',
            'nama21' => 'nullable',
            'street1' => 'nullable',
            'addit1' => 'nullable',
            'postal_code1' => 'nullable',
            'po_box1' => 'nullable',
            'tax1' => 'nullable',
            'mobile1' => 'nullable',
            'home1' => 'nullable',
            'fax1' => 'nullable',
            'address_code12' => 'nullable',
            'title2' => 'nullable',
            'negara2' => 'nullable',
            'kode_county2' => 'nullable',
            'kota2' => 'nullable',
            'email2' => 'nullable',
            'telp2' => 'nullable',
            'npwp2' => 'nullable',
            'short_name2' => 'nullable',
            'nama12' => 'nullable',
            'nama22' => 'nullable',
            'street2' => 'nullable',
            'addit2' => 'nullable',
            'postal_code2' => 'nullable',
            'po_box2' => 'nullable',
            'tax2' => 'nullable',
            'mobile2' => 'nullable',
            'home2' => 'nullable',
            'fax2' => 'nullable',
            'address_code13' => 'nullable',
            'title3' => 'nullable',
            'negara3' => 'nullable',
            'kode_county3' => 'nullable',
            'kota3' => 'nullable',
            'email3' => 'nullable',
            'telp3' => 'nullable',
            'npwp3' => 'nullable',
            'short_name3' => 'nullable',
            'nama13' => 'nullable',
            'nama23' => 'nullable',
            'street3' => 'nullable',
            'addit3' => 'nullable',
            'postal_code3' => 'nullable',
            'po_box3' => 'nullable',
            'tax3' => 'nullable',
            'mobile3' => 'nullable',
            'home3' => 'nullable',
            'fax3' => 'nullable',

            //kd06
            'kd6no_cust' => 'nullable',
            'sd' => 'nullable',
            'biz_type_p1' => 'nullable',
            'nama_agent1' => 'nullable',
            'nama_agent2' => 'nullable',
            'nama_agent3' => 'nullable',
            'nama_agent4' => 'nullable',
            'nama_agent5' => 'nullable',
            'kode_brand1' => 'nullable',
            'kode_brand2' => 'nullable',
            'kode_brand3' => 'nullable',
            'kode_brand4' => 'nullable',
            'kode_brand5' => 'nullable',
            'long_desc1' => 'nullable',
            'long_desc2' => 'nullable',
            'long_desc3' => 'nullable',
            'long_desc4' => 'nullable',
            'long_desc5' => 'nullable',
            'kd5negara1' => 'nullable',
            'negara2' => 'nullable',
            'negara3' => 'nullable',
            'negara4' => 'nullable',
            'negara5' => 'nullable',
            'allowance_qty' => 'nullable',
            'tax' => 'nullable',
            'assigment' => 'nullable',
            'del_con' => 'nullable',
            'payterm' => 'nullable',
            'kurs' => 'nullable',
            'satuan' => 'nullable',
            'sales' => 'nullable',
            'status' => 'nullable',
            'from' => 'nullable',
            'staff_member' => 'nullable',
            'to' => 'nullable',
            'pc' => 'nullable',
            'print' => 'nullable',

            // kd11
            'sd1' => 'nullable',
            'sg1' => 'nullable',
            'association_no1' => 'nullable',
            'kd11no_cust' => 'nullable',
            'status1' => 'nullable',
            'validity_from1' => 'date|nullable',
            'validity_to1' => 'date|nullable',
            'central_regu1' => 'nullable',
            'conditions1' => 'nullable',
            'sd2' => 'nullable',
            'sg2' => 'nullable',
            'association_no2' => 'nullable',
            'status2' => 'nullable',
            'validity_from2' => 'date|nullable',
            'validity_to2' => 'date|nullable',
            'central_regu2' => 'nullable',
            'conditions2' => 'nullable',
            'sd3' => 'nullable',
            'sg3' => 'nullable',
            'association_no3' => 'nullable',
            'status3' => 'nullable',
            'validity_from3' => 'date|nullable',
            'validity_to3' => 'date|nullable',
            'central_regu3' => 'nullable',
            'conditions3' => 'nullable',

            // kd14
            'kd14no_cust' => 'nullable',
            'nama_cp1' => 'nullable',
            'nama_cp2' => 'nullable',
            'nama_cp3' => 'nullable',
            'jabatan_cp1' => 'nullable',
            'jabatan_cp2' => 'nullable',
            'jabatan_cp3' => 'nullable',
            'phone_cp1' => 'nullable',
            'phone_cp2' => 'nullable',
            'phone_cp3' => 'nullable',
            'email_cp1' => 'nullable',
            'email_cp2' => 'nullable',
            'email_cp3' => 'nullable',
            'sd_cp1' => 'nullable',
            'sd_cp2' => 'nullable',
            'sd_cp3' => 'nullable',
            'sg_cp1' => 'nullable',
            'sg_cp2' => 'nullable',
            'sg_cp3' => 'nullable',
            'function_cp1' => 'nullable',
            'function_cp2' => 'nullable',
            'function_cp3' => 'nullable',
            'role_cp1' => 'nullable',
            'role_cp2' => 'nullable',
            'role_cp3' => 'nullable',
            'sinc_cp1' => 'date|nullable',
            'sinc_cp2' => 'date|nullable',
            'sinc_cp3' => 'date|nullable',
            'add_addr_cp1' => 'nullable',
            'add_addr_cp2' => 'nullable',
            'add_addr_cp3' => 'nullable',
            'mobile_cp1' => 'nullable',
            'mobile_cp2' => 'nullable',
            'mobile_cp3' => 'nullable',
            'cp1' => 'nullable',
            'cp2' => 'nullable',
            'cp3' => 'nullable',
        ];
    }
}
