<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class MasterQardCreateRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'form_request_development_id' => 'nullable',
            'form_dev_sales_id' => 'nullable',
            'ws3_id' => 'nullable',
            'ws5_id' => 'nullable',
            'user_id' => 'nullable',
            'tgl_masuk' => 'date',
            'delivery_time' => 'date',
            'tgl_selesai_report' => 'date',
            'index' => 'nullable',
            'tgl_selesai_proses' => 'date',
            'article_greige' => 'nullable',
            'article_finish' => 'nullable',
            'quality' => 'nullable',
            'costruction_no_benang' => 'nullable',
            'costruction_tetal' => 'nullable',
            'finish_width' => 'numeric|nullable',
            'qty' => 'numeric|nullable',
            'f-method' => 'nullable',
            'weave' => 'nullable',
            'width_greige' => 'numeric|nullable',
            'supplier' => 'nullable', 
            'customer' => 'nullable',
            'purpose' => 'nullable',
            'marketing_sales' => 'nullable',
            'target_quality' => 'nullable',
            'greige_construction' => 'nullable',
            'greige_width' => 'numeric|nullable',
            'greige_weight_1' => 'numeric|nullable',
            'greige_weight_2' => 'numeric|nullable',
            'greige_weight_3' => 'numeric|nullable',
            'greige_weight_avg' => 'numeric|nullable',
            'greige_tensile_lusi_1' => 'numeric|nullable',
            'greige_tensile_lusi_2' => 'numeric|nullable',
            'greige_tensile_lusi_3' => 'numeric|nullable',
            'greige_tensile_lusi_avg' => 'numeric|nullable',
            'greige_tensile_pakan_1' => 'numeric|nullable',
            'greige_tensile_pakan_2' => 'numeric|nullable',
            'greige_tensile_pakan_3' => 'numeric|nullable',
            'greige_tensile_pakan_avg' => 'numeric|nullable',
            'greige_tearing_lusi_1' => 'numeric|nullable',
            'greige_tearing_lusi_2' => 'numeric|nullable',
            'greige_tearing_lusi_3' => 'numeric|nullable',
            'greige_tearing_lusi_avg' => 'numeric|nullable',
            'greige_tearing_pakan_1' => 'numeric|nullable',
            'greige_tearing_pakan_2' => 'numeric|nullable',
            'greige_tearing_pakan_3' => 'numeric|nullable',
            'greige_tearing_pakan_avg' => 'numeric|nullable',
            'pfd_construction' => 'nullable',
            'pfd_width' => 'numeric|nullable',
            'pfd_weight_1' => 'numeric|nullable',
            'pfd_weight_2' => 'numeric|nullable',
            'pfd_weight_3' => 'numeric|nullable',
            'pfd_tensile_lusi_1' => 'numeric|nullable',
            'pfd_tensile_lusi_2' => 'numeric|nullable',
            'pfd_tensile_lusi_3' => 'numeric|nullable',
            'pfd_tensile_pakan_1' => 'numeric|nullable',
            'pfd_tensile_pakan_2' => 'numeric|nullable',
            'pfd_tensile_pakan_3' => 'numeric|nullable',
            'pfd_tearing_lusi_1' => 'numeric|nullable',
            'pfd_tearing_lusi_2' => 'numeric|nullable',
            'pfd_tearing_lusi_3' => 'numeric|nullable',
            'pfd_tearing_pakan_1' => 'numeric|nullable',
            'pfd_tearing_pakan_2' => 'numeric|nullable',
            'pfd_tearing_pakan_3' => 'numeric|nullable',
            'pfd_shrinkage_lusi_1' => 'numeric|nullable',
            'pfd_shrinkage_lusi_2' => 'numeric|nullable',
            'pfd_shrinkage_lusi_3' => 'numeric|nullable',
            'pfd_shrinkage_pakan_1' => 'numeric|nullable',
            'pfd_shrinkage_pakan_2' => 'numeric|nullable',
            'pfd_shrinkage_pakan_3' => 'numeric|nullable',
            'pfd_lebar_after_shrinkage' => 'numeric|nullable',
            'pfd_stretch' => 'numeric|nullable',
            'pfd_pilling_resistance' => 'numeric|nullable',
            'finish_construction' => 'numeric|nullable',
            'finish_width_finish' => 'numeric|nullable',
            'finish_weight_1' => 'numeric|nullable',
            'finish_weight_2' => 'numeric|nullable',
            'finish_weight_3' => 'numeric|nullable',
            'finish_weight_avg' => 'numeric|nullable',
            'finish_tensile_lusi_1' => 'numeric|nullable',
            'finish_tensile_lusi_2' => 'numeric|nullable',
            'finish_tensile_lusi_3' => 'numeric|nullable',
            'finish_tensile_lusi_avg' => 'numeric|nullable',
            'finish_tensile_pakan_1' => 'numeric|nullable',
            'finish_tensile_pakan_2' => 'numeric|nullable',
            'finish_tensile_pakan_3' => 'numeric|nullable',
            'finish_tensile_pakan_avg' => 'numeric|nullable',
            'finish_tearing_lusi_1' => 'numeric|nullable',
            'finish_tearing_lusi_2' => 'numeric|nullable',
            'finish_tearing_lusi_3' => 'numeric|nullable',
            'finish_tearing_lusi_avg' => 'numeric|nullable',
            'finish_tearing_pakan_1' => 'numeric|nullable',
            'finish_tearing_pakan_2' => 'numeric|nullable',
            'finish_tearing_pakan_3' => 'numeric|nullable',
            'finish_tearing_pakan_avg' => 'numeric|nullable',
            'finish_slippage' => 'numeric|nullable',
            'finish_shringkage_lusi_1' => 'numeric|nullable',
            'finish_shringkage_lusi_2' => 'numeric|nullable',
            'finish_shringkage_lusi_3' => 'numeric|nullable',
            'finish_shringkage_lusi_avg' => 'numeric|nullable',
            'finish_shringkage_pakan_1' => 'numeric|nullable',
            'finish_shringkage_pakan_2' => 'numeric|nullable',
            'finish_shringkage_pakan_3' => 'numeric|nullable',
            'finish_lebar_after_shrinkage' => 'numeric|nullable',
            'finish_stretch' => 'numeric|nullable',
            'finish_pilling_resistance' => 'numeric|nullable',
            'grey_construction_fix' => 'numeric|nullable',
            'grey_width_fix' => 'numeric|nullable',
            'grey_weight_fix' => 'numeric|nullable',
            'grey_tensile_lusi_fix' => 'numeric|nullable',
            'grey_tensile_pakan_fix' => 'numeric|nullable',
            'grey_tearing_lusi_fix' => 'numeric|nullable',
            'grey_tearing_pakan_fix' => 'numeric|nullable',
            'pfp_construction_fix' => 'nullable',
            'pfp_width_fix' => 'numeric|nullable',
            'pfp_weight_fix' => 'numeric|nullable',
            'pfp_tensile_lusi_fix' => 'numeric|nullable',
            'pfp_tensile_pakan_fix' => 'numeric|nullable',
            'pfp_tearing_lusi_fix' => 'numeric|nullable',
            'pfp_tearing_pakan_fix'=> 'numeric|nullable',
            'finish_construction_fix' => 'nullable',
            'finish_width_fix' => 'numeric|nullable',
            'finish_weight_fix' => 'numeric|nullable',
            'finish_tensile_lusi_fix' => 'numeric|nullable',
            'finish_tensile_pakan_fix' => 'numeric|nullable',
            'finish_tearing_lusi_fix' => 'numeric|nullable',
            'finish_tearing_pakan_fix' => 'numeric|nullable',
            'finish_slippage_fix' => 'numeric|nullable',
            'finish_shrinkage_lusi_fix' => 'numeric|nullable',
            'finish_shrinkage_pakan_fix' => 'numeric|nullable',
            'finish_n-wdt' => 'numeric|nullable',
            'finish_none' => 'numeric|nullable',
            'finish_stretch_fix' => 'numeric|nullable',
            'finish_skewing_bowing' => 'numeric|nullable',
            'comment1' => 'nullable',
            'comment2' => 'nullable',
            'comment3' => 'nullable',
            'comment4' => 'nullable',
            'comment5' => 'nullable',
            'comment6' => 'nullable',
            'comment7' => 'nullable',
            'comment8' => 'nullable',
            'comment9' => 'nullable',
            'comment10' => 'nullable',
            'comment11' => 'nullable',
            'comment12' => 'nullable',
            'comment13' => 'nullable',
            'comment14' => 'nullable',
            'comment15' => 'nullable',
            'comment16' => 'nullable',
            'comment17' => 'nullable',
            'comment18' => 'nullable',
            'comment19' => 'nullable',
            'comment20' => 'nullable',
            'comment21' => 'nullable',
            'comment22' => 'nullable',
            'comment23' => 'nullable',
            'comment24' => 'nullable',
            'flow_code' => 'numeric|nullable',
            'note_wid_1' => 'nullable',
            'tgl_release' => 'date',
            'nots' => 'nullable',
            'status_actual_time' => 'nullable',
            'status_sistem' => 'nullable',
            'lama_proses' => 'numeric|nullable',
            'lama_report' => 'numeric|nullable',
            'lama_release' => 'numeric|nullable',
            'total_waktu' => 'numeric|nullable',
            'product_type' => 'numeric|nullable',
        ];
    }
}
